"""site content: blog posts, neighborhoods, pages

Revision ID: aeb65e542634
Revises: e1a7c3f9b204
Create Date: 2026-09-01 08:10:05.552541

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'aeb65e542634'
down_revision: str | Sequence[str] | None = 'e1a7c3f9b204'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Creates three new tables only. Autogenerate also proposed index changes
    # on oauth_states and whatsapp_threads — pre-existing model/DB drift,
    # unrelated to this change, deliberately left out.
    op.create_table('blog_posts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content_html', sa.Text(), nullable=False),
    sa.Column('excerpt_html', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('wp_id', sa.Integer(), nullable=True),
    sa.Column(
        'created_at',
        sa.DateTime(),
        server_default=sa.text('(CURRENT_TIMESTAMP)'),
        nullable=False,
    ),
    sa.Column(
        'updated_at',
        sa.DateTime(),
        server_default=sa.text('(CURRENT_TIMESTAMP)'),
        nullable=False,
    ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_posts_published'), 'blog_posts', ['published'], unique=False)
    op.create_index(op.f('ix_blog_posts_slug'), 'blog_posts', ['slug'], unique=True)
    op.create_index(op.f('ix_blog_posts_wp_id'), 'blog_posts', ['wp_id'], unique=True)
    op.create_table('neighborhoods',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content_html', sa.Text(), nullable=False),
    sa.Column('card_image_url', sa.String(length=1000), nullable=True),
    sa.Column('hero_image_url', sa.String(length=1000), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('wp_id', sa.Integer(), nullable=True),
    sa.Column(
        'created_at',
        sa.DateTime(),
        server_default=sa.text('(CURRENT_TIMESTAMP)'),
        nullable=False,
    ),
    sa.Column(
        'updated_at',
        sa.DateTime(),
        server_default=sa.text('(CURRENT_TIMESTAMP)'),
        nullable=False,
    ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_neighborhoods_published'),
        'neighborhoods',
        ['published'],
        unique=False,
    )
    op.create_index(op.f('ix_neighborhoods_slug'), 'neighborhoods', ['slug'], unique=True)
    op.create_index(op.f('ix_neighborhoods_wp_id'), 'neighborhoods', ['wp_id'], unique=True)
    op.create_table('site_pages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content_html', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('wp_id', sa.Integer(), nullable=True),
    sa.Column(
        'created_at',
        sa.DateTime(),
        server_default=sa.text('(CURRENT_TIMESTAMP)'),
        nullable=False,
    ),
    sa.Column(
        'updated_at',
        sa.DateTime(),
        server_default=sa.text('(CURRENT_TIMESTAMP)'),
        nullable=False,
    ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_pages_published'), 'site_pages', ['published'], unique=False)
    op.create_index(op.f('ix_site_pages_slug'), 'site_pages', ['slug'], unique=True)
    op.create_index(op.f('ix_site_pages_wp_id'), 'site_pages', ['wp_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_pages_wp_id'), table_name='site_pages')
    op.drop_index(op.f('ix_site_pages_slug'), table_name='site_pages')
    op.drop_index(op.f('ix_site_pages_published'), table_name='site_pages')
    op.drop_table('site_pages')
    op.drop_index(op.f('ix_neighborhoods_wp_id'), table_name='neighborhoods')
    op.drop_index(op.f('ix_neighborhoods_slug'), table_name='neighborhoods')
    op.drop_index(op.f('ix_neighborhoods_published'), table_name='neighborhoods')
    op.drop_table('neighborhoods')
    op.drop_index(op.f('ix_blog_posts_wp_id'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_slug'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_published'), table_name='blog_posts')
    op.drop_table('blog_posts')
    # ### end Alembic commands ###
